# 動態網頁爬蟲 - API Request

* 了解 API Request 用於動態網頁爬蟲的原理
* 能夠使用 API Request 撰寫動態網頁爬蟲

## 作業目標


* 根據範例使用 API 取出 高雄市小港區 2019 年 空氣品質 資料，並用一個適合的資料結構儲存
* Hint: 將所有資料存在一個變數當中

In [3]:
import requests
url = 'https://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx'
payload = {
    '''
    Your Code
    '''
    'ctl05$ddlSite': 14,
    'ctl05$ddlYear': 2015,
    'ctl05$btnQuery': '查詢',
    'ScriptManager1': 'ctl05$UpdatePanel1|ctl05$btnQuery',
    '__VIEWSTATE': 'JmXyVAopX5I9ra9ri6NfXIooPImk7ZQl9CyUJyjNKraMzyG4CIe0EJCcZYE0mHw5kvgo1xPdd3xyHs0I7GsaweZJ/92dnpcli7uB7WJQelpayNhtDcS/I+tR0foHyMRoMNUcIsNd9weId6O/FINIQgD3RIS+61OZWMv0HSgsehVJ/3bXRMt7+XCneI2+dRF2BNpFb+eSXkW6oenunHrzymg9rkbx9iCqw3LsXDASdKEkocqSXqSzYTJXd8P39JNafb55Dqz8TKJKY5A+4ZJx6s1PqP7R1mUvPiUWn6xpvZg1E3Za5V0aUBIwstuBI7QpMCGo7ZENfSR44Pf+XmjHdHqyPWhR8h6F0UbdxudFfFR52SoXvfcdq3U57Ed4i2hcNf+PlMGFIJajyMcSvblT69hhszgY3LumXdMSVEGzDD9inZRqOn9L+PO5C2z4rY7mc4qyRlhsWCv3AlJ1J/MkWsuSrhIJiWwPURuOuUwRwFljUNqftB2N6sWS8tVx6KX5qL7NYJmpNHxHRH8y+i/E3RFwgOzwgcP+IbkESQKyMg2vPlVS9BpsVVhXxC9jI2SE1EVcw2PwehHUeE+W8RkPvUzK6sOYXe2lKHYAPtTM1e2sPulsAGXJRfrB65OT8AS59tCPNFxhneZ/uhuDIsGbzzzwu7yJlJSl2l4rMnEtXhOfsDORby99rPE3ZRHQyZ8t59rc1HB5BgNGIV0OGWG7YIQUEAk2N8/O1jeQTwvAJsKf5pdlXvO0DSTjoemOKz+A/JKGZK5L1oKjcRNbpfuuq8XmvQJn7Vrx+0oWPICFpYb6svlYo4HMzNuByr8JPhESIj5Kl7A1ka768iaPh8hdvj8Qe7Xe6pNgEdDKutRehk1B53g68PIaJT9KGcn2uQ+PjoQMqAlkQtq3goDhkkZE3EKxX+YDrGx7OZTDLW91QzmQUG9KUbqi7uaBZ6OqI+kK2rbYLfVA682Y5BG9DgjRACTGXIhMslfGhtR4+BYQja6D6UAV0v1noUhx3iWrscysM9GCFMZ9HWmrgKvrzCRZ22vCSQ0utzvYxO4wkdCUu6N2rctJQww0H61mF68yV5FUyqqjJOBi0LTn+bgR45FKQvEMiTQzrqD0+dHcb/QRPrcIw5qFaId9fXu0kAeNOOET/UjFSjUKFL/p2BPwtIEblUkARYKXjz266067mOSr6XRIvwIcKpN9om2iQGR+REJaLUNW+W4qXSJQZ9Y8X6YHkwM2d99xZ0L7Er+ICvAwecLYy6c2x/O3J5vOtsuLd+TTCdn1g9sANMuOehIYN7hAFYzauzioFqGJyXXCA9pvs8e+Uoq9ltElUzZ0QjpgHircLHdn5X4KgVt1mZTSQNXzraRkSSO/5o5epQ//XZQ1ctIM2Qpyd5DOPFlfUuFPXuA7RQjDjArQ4G2gmSmtsSjNynZ4VEdsY1bcjUK4jLcSmTJstH5G41VmMPvlSLC1WvCKvLGeHXn7VYgz2KLxX78/aRe/A/S1OlRVlz5tcnTZiQYCmpVnssTpmhc7Ju+RfERVkyLroSHth8Yw5X7KgUHhgZHxeu8X91k2iWLrxK+ouhdX1ZR7wNM53GTVwKq8X3FpzgcgZMZ8eaR0AbZRPrgCtdqYtRPLBsqxxf5TxCbjepv6myz4HSMCsP2iyBDWiXKldmmEmNCQCHiAStkXwm4BqZpHZswzRACp5g2MxH3ql/1dbYE1CZzKuXEh+uhDqXyGrAdszOl20gVYC/aEnnFLYM/BuYOxrk5h0SqNDWMWQsnevry++J/uvwK92faiL4fgzI3fY8DFlbpcrrHAQOAUX0qd8BG7eeKEDpwhhozpu2H3KKGmljpXaYx2hKYIL8B6lxaXEuhwJgw1FgZslRBytP7w++pk2MPXgUAmey/t/AlE5sZ2NEiok7GScxVT3HKuCQLKmze4KlvHqlUxcoRUUTGsFXLnFvUD71p9kyyZsuD/uagLdUDSyZZl9SKYBEN93kuGdwxKUVuxURz5DLizqjlGcB/GTfwHM202Pc05M4E0W8dJdeZBfBqhhd66fHWYipCFcTfjzJWf+QxPM5X4/E4ZKwQwiZm54Nsd6PDRPXLqkwcW31Srg6V44tPEXVu7Obuj51dep03D6C3GeloshtH1KLRzH7DDViF16ywm9yikkWbc6zJ8wMrwd13yOfvdD9lrg20kWD3GJ5z8f7p5uu6+pkOi/eRMzW9UPnLEYR8ttKcYAz7ZaubYsGVrRT9zWanbRf6E+JixXEtou3W2/NupHtycOUIvJTARVK8r2bbCsgbbIVeUyQjYP7kbnkB9Eud7YlLec4uKkPyIVRdLk9SHKtj0t+3J+LkM4HLPvXsJ9JkXpTDuwnKZIABioX8Ri07zywGPo5iP5r4W2G4DW0lBEnK7sA3i6ZjNY20b6sIkzAiCthW69+tnhR/zwSQu+Ikna0xb+0xVJ906lm1Eb0UN0BvJdM5sPcZ3xtJ0oEmlgPNq7190YSPzG2JBS3c4Jr03bNVglxDafgV650tNFDe2s6YV2gXXyj6EIqXh59ZXrtg3PVFYP0kxABIW7kWLONABx8lIzDvQCYi+7TeHvOFWfCTD7kCL5WUMEG/N3lRSrXtV9DDhAdiSjc2YNiUTNy1eg+uSoHS0iVNkSfsA3WC6UQXK8X1HQETSv/DGbwiprdJbv+6CBKt3j7HxwN/WnUguBfQ6sR/W3sn+kV73BKYiioEM8v8IfReyNhcblJ6CMnVMcnF7/MZsjZzASGbqTeiNTT4HSRMs/z3C5Sxrg5AI81775n3hLhSIEmAFzE3Gg7AZqlmDyn/Y3asVfQPnsmeBL64kEuPAkQAxKHXPkqXoUGNUYcdyxmHmIdqHGlMq+01J34VC+FPqaMKFlNe7/NiCj4j7ftTj+d5L37NtxbI57EkpTiH6Hf1nWujUx7jv3t+IUy3xT7Ng0w8QyDW18FC/xrPskVMrD/Ps0CqVI5mL2NosTd+K5QuPM0N/N/ZcRueLHR4qktggBt+Q4KqAnRkqUSKQnpJMh+e4IDOIo5nIehaoc0TxnDe6qTlqH/U8dYA28F+NStmDU1evmupbMDjkPz2RdljGs86zcexmTP4T1bb4xAE5F1aHcnjctFa28ASUacCGP7PjdPfOagimhlwide4NiubR94DcZDy9iunWtT8=',
    '__VIEWSTATEGENERATOR': '0C858E1A',
    '__EVENTVALIDATION': 'gEpZUOTcabNNcblKBVaWr0ElIeZplRIkETTXAbnBanuNYFa2PC2GrSLOB8T6jT2fNu8Y5BmrSZgI8678gNe76TyrO4oE23DGtaHdRUp2cNCQUsrwZVBZphtckmsnCucYskQxfxmTgA+qWyvQkOKUEVJLFR0lpVgrG01twnJGNEQrq2bsGyv9SOgEdiO4z4NN730wGpletad0hB8BBn3eA2PbrBgAa3ej96TgaZDTMF4pwSgl8U5Y2155qQtVWQw5+/6doRKCwvlgMYfRwAAO7DNMQplBC49mMhYJpRcACjdiK03L2ed++6zPPx7AteuooZnMSbGiAY8Y9sJFtK8+vumO3WpkjI7ntzgGVB+IgiVx8Xlqi8jBJ0oWLCofsARCtIUquDsAbs0ARBTdS1M4WFMn5MP/cfU8zMDC78Qbi+Eihh+ueM5DR+fq7LR0wQixgwuXwy2B8AcHCgYR46a+Wxz1951lmFdlVsFCWFCUUTRdDvT3XBxtG/ORp76vIHk3k0xe2cg24+F3TvG1AYHsyCdv4e+3hCCXaT4c1q+O7YovGApY2sgF/tE172fF2BRj+qLe5kUTxY6wrHxUqpFfxq8iTVth6Psaf3EjkAswyqBEibOfAWO2MQdvbLtoVX8MNNOp1Ew7Dj97gVSoKbOr/clDHvcBaNDUacF0twUdytQn+c0haup8CRT6/BQvdob4nTcrBSC+WUqGfjYtDMdElZW7aCOAWQEIU0HPLvbPnONJF8yNbOyXTAz2eYZhhxLle9ENiEXYzYDgDkJoPg+y7TvSLywx8aEVJvNJYvfAo4ybrgr6sbzJNwB3w82/oXibPVh96KEssJjtfrDubZ3Y5Xghus0xLvYT9uXRyXUWitMJn7LsCk8iWwrFk1lA0yf8z+x9NSiKVxFD/RNxCcM82ejzjqFxNDFlCUwOwVmbVPK/GQ9LQ08+Ih0j/t+XhoPfnpD5afdsXy9bhnQLfqia0NsenMw='
}
r = requests.post(url, data=payload)
r.status_code

200

![](https://imgur.com/obLkbFe.jpg)

In [4]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(r.text, 'html.parser')
table = soup.find('table', class_='TABLE_G')
print(table)

<table align="Center" border="1" cellpadding="3" cellspacing="0" class="TABLE_G" id="ctl05_gv" rules="all" style="border-color:Black;border-width:1px;border-style:None;border-collapse:collapse;">
<tr style="color:Black;font-weight:normal;">
<th scope="col">監測項目</th><th scope="col">單位</th><th scope="col">監測日期</th><th scope="col">監測值</th><th scope="col">標註</th>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">SO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2015/01</td><td>2.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/02</td><td>2.60</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/03</td><td>2.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/04</td><td>2.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/05</td><td>3.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/06</td><td>3</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/07</td><td>3</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/08</td><td>2.70</td><td>無效</td>
</tr><tr style="color:Black;">
<td>2015/09</td><td> </td><td>無效</td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/10</td><td>2.20</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/11</td><td>2.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/12</td><td>2.90</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">CO</td><td class="no-alt" rowspan="12" valign="top">ppm</td><td>2015/01</td><td>0.47</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/02</td><td>0.46</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/03</td><td>0.48</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/04</td><td>0.43</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/05</td><td>0.47</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/06</td><td>0.37</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/07</td><td>0.33</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/08</td><td>0.32</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/09</td><td>0.38</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/10</td><td>0.29</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/11</td><td>0.37</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/12</td><td>0.40</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">O3</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2015/01</td><td>35.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/02</td><td>35.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/03</td><td>34.50</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/04</td><td>37</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/05</td><td>28.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/06</td><td>23.20</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/07</td><td>28.50</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/08</td><td>24.10</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/09</td><td>37.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/10</td><td>41.60</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/11</td><td>34.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/12</td><td>31.40</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">PM10</td><td class="no-alt" rowspan="12" valign="top">μg/m3</td><td>2015/01</td><td>49</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/02</td><td>46</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/03</td><td>39</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/04</td><td>38</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/05</td><td>34</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/06</td><td>34</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/07</td><td>33</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/08</td><td>26</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/09</td><td>31</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/10</td><td>34</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/11</td><td>29</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/12</td><td>36</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NOx</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2015/01</td><td>21.53</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/02</td><td>20.10</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/03</td><td>23.21</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/04</td><td>19.23</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/05</td><td>23.17</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/06</td><td>19.57</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/07</td><td>16.36</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/08</td><td>16.13</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/09</td><td>15.50</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/10</td><td>10.93</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/11</td><td>14.06</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/12</td><td>15.82</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2015/01</td><td>6.34</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/02</td><td>4.49</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/03</td><td>5.58</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/04</td><td>3.18</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/05</td><td>5.58</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/06</td><td>4.14</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/07</td><td>3.18</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/08</td><td>3.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/09</td><td>2.84</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/10</td><td>1.81</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/11</td><td>2.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/12</td><td>3.07</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2015/01</td><td>15.19</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/02</td><td>15.60</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/03</td><td>17.63</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/04</td><td>16.05</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/05</td><td>17.59</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/06</td><td>15.42</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/07</td><td>13.17</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/08</td><td>12.73</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/09</td><td>12.65</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/10</td><td>9.11</td><td> </td>
</tr><tr style="color:Black;">
<td>2015/11</td><td>11.26</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2015/12</td><td>12.74</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">THC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr class="ALT" style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">NMHC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr style="color:Black;">
<td style="white-space:nowrap;">CH4</td><td>ppm</td><td> </td><td> </td><td>無此測項</td>
</tr>
</table>

In [14]:
'''
Your Code
'''
# #==2=======
# d = {} #列表
# key = ''
# date = ''
# items = table.find_all('td')
# # print(items) #=====
# # <td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">SO2</td>
# # <td class="no-alt" rowspan="12" valign="top">ppb</td>
# # <td>2019/01</td> <td>4.10</td> <td> </td>
# # <td>2019/02</td> <td>3.30</td> <td> </td>
# for item in items:
# #     print(item)
# #     print(item.attrs)
# #     <td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">SO2</td>
# #     {'class': ['no-alt'], 'rowspan': '12', 'valign': 'top', 'style': 'white-space:nowrap;'}
# #     <td class="no-alt" rowspan="12" valign="top">ppb</td>
# #     {'class': ['no-alt'], 'rowspan': '12', 'valign': 'top'}
# #     <td>2019/01</td>
# #     {}
# #     <td>4.10</td>
# #     {}
# #     <td> </td>
# #     {}

#     if 'style' in item.attrs: #attrs字典
#         #attrs參數是dict類型，傳遞到Comment函數的時候前面加兩個星號轉成可變參數列表
#         #<td class="no-alt" rowspan="12" valign="top" style="white-space:nowrap;">SO2</td>
#         key = item.text
#         d[key]={} #表頭
#     elif 'class' not in item.attrs:
# #     <td>2019/01</td>
# #     {}
#         if item.text.strip() != '': #不等於空白
#         #strip() 方法用於移除字符串頭尾指定的字符（默認為空格或換行符）或字符序列。
#         #注意：該方法只能刪除開頭或是結尾的字符，不能刪除中間部分的字符。
#             # print(item.text)
#             if '/'in item.text: #日期
#                 date = item.text
#             else:
#                 # print(item.text)
#                 d[key][date] = item.text #資料
# # print(d)
# #==3=======
# items=[]
# monitor_items=[]

# trs=table.find_all('tr')
# for tr in trs:
# # <tr style="color:Black;"> #<<<5
# #    <td class="no-alt" rowspan="12" valign="top" style="white-space:nowrap;">SO2</td>
# #     <td class="no-alt" rowspan="12" valign="top">ppb</td>
# #     <td>2017/01</td>
# #     <td>2.20</td>
# #     <td>&nbsp;</td>
# # </tr>
# # <tr class="ALT" style="color:Black;">  #<<<3
# #  <td>2017/02</td>
# #     <td>2.40</td>
# #     <td>&nbsp;</td>
# # </tr>

# #     print(len(tr.find_all('td')))
#     tds=tr.find_all('td')
#     if len(tds)>0:
#         if len(tds)==5:
#             items.append(tds[0].text) #第一組 0監測項目,1單位, 2日期, 3監測值,
#             # append() 方法用於在列表末尾添加新的對象
# #             print(tds[3].text) #===
#             monitor_item={}
#             monitor_items.append(monitor_item)
#             monitor_item[tds[2].text]=tds[3].text
# #             print(tds[3].text) #=== 值
# #             print( monitor_item[tds[2].text]) #=== 值
#         if len(tds)==3: #日期
#             monitor_item[tds[0].text]=tds[1].text
# #             print(monitor_item[tds[0].text])
# #     print(monitor_item) #===
# #     print("====================") #===
# # print(monitor_items) #監測值
# # print(items) #監測項目
# # print("====================")
# d={}
# for item, monitor in zip(items, monitor_items):
#     #zip()函數用於將可迭代的對像作為參數，將對像中對應的元素打包成一個個元組，然後返回由這些元組組成的列表。
#     d[item]=monitor
# print(d)

#===3==========================
d = {}
for tr in table.find_all('tr')[1:]: #[1:]標題在 0 省略
# <tr style="color:Black;font-weight:normal;">
# <th scope="col">監測項目</th><th scope="col">單位</th><th scope="col">監測日期</th><th scope="col">監測值</th><th scope="col">標註</th>
# </tr>
    td = tr.find_all('td')
    if len(td) == 5:
        Head = td[0].text.strip()
        d[Head] ={}
        Date = td[2].text.strip()
        Value = td[3].text.strip()
        d[Head][Date] = Value
    elif len(td) == 3:
        Date = td[0].text.strip()
        Value = td[1].text.strip()
        d[Head][Date] = Value
# print(d)
d #直式顯示

{'SO2': {'2015/01': '2.60',
  '2015/02': '2.60',
  '2015/03': '2.40',
  '2015/04': '2.70',
  '2015/05': '3.10',
  '2015/06': '3',
  '2015/07': '3',
  '2015/08': '2.70',
  '2015/09': '',
  '2015/10': '2.20',
  '2015/11': '2.80',
  '2015/12': '2.90'},
 'CO': {'2015/01': '0.47',
  '2015/02': '0.46',
  '2015/03': '0.48',
  '2015/04': '0.43',
  '2015/05': '0.47',
  '2015/06': '0.37',
  '2015/07': '0.33',
  '2015/08': '0.32',
  '2015/09': '0.38',
  '2015/10': '0.29',
  '2015/11': '0.37',
  '2015/12': '0.40'},
 'O3': {'2015/01': '35.80',
  '2015/02': '35.50',
  '2015/03': '34.50',
  '2015/04': '37',
  '2015/05': '28.20',
  '2015/06': '23.20',
  '2015/07': '28.50',
  '2015/08': '24.10',
  '2015/09': '37.60',
  '2015/10': '41.60',
  '2015/11': '34.10',
  '2015/12': '31.40'},
 'PM10': {'2015/01': '49',
  '2015/02': '46',
  '2015/03': '39',
  '2015/04': '38',
  '2015/05': '34',
  '2015/06': '34',
  '2015/07': '33',
  '2015/08': '26',
  '2015/09': '31',
  '2015/10': '34',
  '2015/11': '29',
  '2015/12': '36'},
 'NOx': {'2015/01': '21.53',
  '2015/02': '20.10',
  '2015/03': '23.21',
  '2015/04': '19.23',
  '2015/05': '23.17',
  '2015/06': '19.57',
  '2015/07': '16.36',
  '2015/08': '16.13',
  '2015/09': '15.50',
  '2015/10': '10.93',
  '2015/11': '14.06',
  '2015/12': '15.82'},
 'NO': {'2015/01': '6.34',
  '2015/02': '4.49',
  '2015/03': '5.58',
  '2015/04': '3.18',
  '2015/05': '5.58',
  '2015/06': '4.14',
  '2015/07': '3.18',
  '2015/08': '3.40',
  '2015/09': '2.84',
  '2015/10': '1.81',
  '2015/11': '2.80',
  '2015/12': '3.07'},
 'NO2': {'2015/01': '15.19',
  '2015/02': '15.60',
  '2015/03': '17.63',
  '2015/04': '16.05',
  '2015/05': '17.59',
  '2015/06': '15.42',
  '2015/07': '13.17',
  '2015/08': '12.73',
  '2015/09': '12.65',
  '2015/10': '9.11',
  '2015/11': '11.26',
  '2015/12': '12.74'},
 'THC': {'': ''},
 'NMHC': {'': ''},
 'CH4': {'': ''}}

In [8]:
import pandas as pd
pd.DataFrame(d)

          SO2    CO     O3 PM10    NOx    NO    NO2  THC NMHC  CH4
2015/01  2.60  0.47  35.80   49  21.53  6.34  15.19  NaN  NaN  NaN
2015/02  2.60  0.46  35.50   46  20.10  4.49  15.60  NaN  NaN  NaN
2015/03  2.40  0.48  34.50   39  23.21  5.58  17.63  NaN  NaN  NaN
2015/04  2.70  0.43     37   38  19.23  3.18  16.05  NaN  NaN  NaN
2015/05  3.10  0.47  28.20   34  23.17  5.58  17.59  NaN  NaN  NaN
2015/06     3  0.37  23.20   34  19.57  4.14  15.42  NaN  NaN  NaN
2015/07     3  0.33  28.50   33  16.36  3.18  13.17  NaN  NaN  NaN
2015/08  2.70  0.32  24.10   26  16.13  3.40  12.73  NaN  NaN  NaN
2015/09        0.38  37.60   31  15.50  2.84  12.65  NaN  NaN  NaN
2015/10  2.20  0.29  41.60   34  10.93  1.81   9.11  NaN  NaN  NaN
2015/11  2.80  0.37  34.10   29  14.06  2.80  11.26  NaN  NaN  NaN
2015/12  2.90  0.40  31.40   36  15.82  3.07  12.74  NaN  NaN  NaN
          NaN   NaN    NaN  NaN    NaN   NaN    NaN